### PR TITLE
Add environment variable for bearer auth token

### PR DESCRIPTION
**Pull request by hixichen**
We are using vaku for folder list and copy. vaku is a very useful tool for the vault ecosystem. 
However, our internal network has edge gateway which requires valid bearer token. 

Everytime, we need to ssh into jump box to run the script with vaku. 

It would be great that if vaku supports adding auth bearer token environment into Vault request header.

### CODE REVIEW

**Comment by hixichen** [comment]
let me know what do you think?
Will update the test later.

**Comment by lingrino** [comment]
Thanks for the idea! I agree that this is useful and something vaku could support. I'd like to see a test that just verifies a vault request includes the header if the env var is set. Is `BEARER_AUTH_TOKEN` a standard key for this token or something you chose? If it's non-standard I think we should prefer a prefixed key like `VAULT_BEARER_AUTH_TOKEN` so that we don't overlap.

**Comment by lingrino** [comment]
I'm closing this as stale but feel free to reopen if it's still being worked on. Thank you!

**Comment by hixichen** [comment]
I complied a binary for internal usage.

**Pull request closed without merging**
