### PR TITLE
Copy commands can copy when source and target differ in address / namespace / or token

### PR DESCRIPTION
**Pull request by shwuandwing**
This enhancements enables copying secrets between Vault clusters.

### CODE REVIEW

**Comment by lingrino** [comment]
@shwuandwing This is great contribution, thank you! I'm out of town this week but I will do my best to get it reviewed by the end of the week.

**Comment by lingrino** [comment]
@shwuandwing Tests are failing on `gofmt`. You can run `gofmt -l -w -s ./` and commit those changes or give me access to the fork and I'll add that.

**Comment by shwuandwing** [comment]
Got everything to work!

**Comment by shwuandwing** [comment]
I also granted access to the fork if you need anything else.

**Pull request merged**
